<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-02-24 07:28
=======
# Generated by Django 5.0.1 on 2024-02-23 23:52
>>>>>>> 4d0bbd404959734f037501703e75599a01a3ee44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
