<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-02-24 07:28
=======
# Generated by Django 5.0.1 on 2024-02-23 23:53
>>>>>>> 4d0bbd404959734f037501703e75599a01a3ee44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='post', max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted')], default=('PUBLIC', 'Public'), max_length=20)),
=======
                ('type', models.CharField(default='post', max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted')], default=('PUBLIC', 'Public'), max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
>>>>>>> 4d0bbd404959734f037501703e75599a01a3ee44
                ('title', models.CharField(default='', max_length=255)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(default='', max_length=50)),
                ('content', models.TextField(default='')),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
    ]
