# Generated by Django 5.0.1 on 2024-02-20 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('type', models.CharField(default='post', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('id', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('source', models.URLField(default='')),
                ('origin', models.URLField(default='')),
                ('description', models.TextField(default='')),
                ('content_type', models.CharField(default='', max_length=50)),
                ('content', models.TextField(default='')),
                ('count', models.IntegerField(default=0)),
                ('comments', models.CharField(default='', max_length=255)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted')], default='UNLISTED', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
    ]
