# Generated by Django 5.0.1 on 2024-02-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='authorId',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', max_length=20),
        ),
    ]
