# Generated by Django 5.0.1 on 2024-02-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owncomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='hascomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='hascomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='ownlike',
            name='like',
        ),
        migrations.RemoveField(
            model_name='makespost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='makespost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='owncomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ownlike',
            name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='public',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='HasComment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='MakesPost',
        ),
        migrations.DeleteModel(
            name='OwnComment',
        ),
        migrations.DeleteModel(
            name='OwnLike',
        ),
    ]
