# Generated by Django 5.0.1 on 2024-02-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_owncomment_comment_remove_hascomment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='UNLISTED', max_length=20),
        ),
    ]
