# Generated by Django 5.0.1 on 2024-02-22 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='authors.author')),
                ('id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='authors.author')),
            ],
            options={
                'unique_together': {('id1', 'id2')},
            },
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_set', to='authors.author')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='authors.author')),
            ],
            options={
                'unique_together': {('follower', 'followed')},
            },
        ),
    ]
