# Generated by Django 5.0.1 on 2024-02-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follows',
            name='acceptedRequest',
            field=models.BooleanField(default=False),
        ),
    ]
