# Generated by Django 5.0.1 on 2024-03-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
