# Generated by Django 5.0.1 on 2024-03-18 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('type', models.CharField(default='author', editable=False, max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('displayName', models.CharField(default='', max_length=25)),
                ('url', models.URLField(default='', editable=False)),
                ('github', models.CharField(blank=True, default='', max_length=100)),
                ('profileImage', models.URLField(default='https://i.imgur.com/V4RclNb.png')),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('host', models.URLField(blank=True, default='https://nexapulse2-389a49c0c9f8.herokuapp.com/', null=True)),
                ('isForeign', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
