# Generated by Django 5.0.1 on 2024-02-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_post_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
