# Generated by Django 5.0.1 on 2024-03-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(blank=True, default='https://nexapulse1-7fbca99d2d7b.herokuapp.com/', null=True),
        ),
    ]
