# Generated by Django 5.0.1 on 2024-03-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(default='https://i.imgur.com/V4RclNb.png'),
        ),
    ]
