# Generated by Django 5.0.1 on 2024-02-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_remove_author_name_author_email_author_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='unknown@example.com', max_length=254)),
                ('password', models.CharField(default='', max_length=255)),
                ('github', models.CharField(default='', max_length=100)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='server/profile_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='author',
            name='github',
        ),
        migrations.RemoveField(
            model_name='author',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='author',
            name='password',
        ),
        migrations.RemoveField(
            model_name='author',
            name='profileImage',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
