# Generated by Django 5.0.1 on 2024-03-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
