# Generated by Django 5.0.1 on 2024-03-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_author_github_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(default='author', editable=False, max_length=500),
        ),
    ]
