# Generated by Django 5.0.1 on 2024-02-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_post_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hascomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='owncomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='hascomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='ownlike',
            name='like',
        ),
        migrations.RemoveField(
            model_name='makespost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='makespost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='owncomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ownlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='HasComment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='MakesPost',
        ),
        migrations.DeleteModel(
            name='OwnComment',
        ),
        migrations.DeleteModel(
            name='OwnLike',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
