# Generated by Django 5.0.1 on 2024-03-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_author_displayname_alter_author_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(blank=True, default='https://nexapulse1-7fbca99d2d7b.herokuapp.com/', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(default='https://i.imgur.com/V4RclNb.png', max_length=500),
        ),
    ]
