# Generated by Django 5.0.1 on 2024-02-20 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remove_hascomment_comment_remove_owncomment_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AlterUniqueTogether(
            name='follows',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='follows',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='follows',
            name='follower',
        ),
        migrations.DeleteModel(
            name='FollowedBy',
        ),
        migrations.DeleteModel(
            name='Follows',
        ),
    ]
