# Generated by Django 5.0.1 on 2024-02-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_rename_user_authors_delete_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
