# Generated by Django 5.0.1 on 2024-04-07 00:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_author_host_alter_author_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(blank=True, default='https://nexapulse-25959148b934.herokuapp.com/', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
